# Generated by Django 5.1.2 on 2024-11-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notetakingapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="Note",
        ),
    ]
