# Generated by Django 5.1.2 on 2024-11-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notetakingapp", "0004_alter_note_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="note",
            name="due_date",
        ),
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.CharField(
                choices=[
                    ("Work", "Work"),
                    ("Personal", "Personal"),
                    ("Study", "Study"),
                    ("Other", "Other"),
                ],
                default="Personal",
                max_length=50,
            ),
        ),
    ]
