# Generated by Django 5.1.2 on 2024-11-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notetakingapp", "0003_note_category_note_due_date_note_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.CharField(
                choices=[
                    ("Work", "Work"),
                    ("Personal", "Personal"),
                    ("Study", "Study"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
